name: IEP
version: 1.1.7
api-version: 1.20
author: Efnilite
main: dev.efnilite.iep.IEP
description: Automatically generating, infinitely long elytra parkour.
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  iep:
    description: IEP main command
    usage: /iep
    aliases: [infiniteelytraparkour]